name: raj app conatinerization pipeline
# Trigger -- when this pipeline should start
on:
  push:
    branches:
    - "dev"

# creating multiple jobs
jobs:
  raj-sast-job:
    runs-on: self-hosted
    steps:
      - name: checking docker version and sonarscanner
        run:  |
          pwd
          whoami
          sonar-scanner --version
      - name: fetch git code
        uses: actions/checkout@v4

      #- name: SonarQube Scan
       # uses: SonarSource/sonarqube-scan-action@v2.1.0 # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
        #with:
         # projectBaseDir: .
          #args: >
           # -Dsonar.projectKey=raj-python-project
      
        #env:
          #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          #SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

      - name: using local sonar-scanner
        run:  |
          pwd
          sonar-scanner -D"sonar.projectKey=ashu-python-project" -D"sonar.sources=." -D"sonar.host.url=${{ vars.SONAR_HOST_URL }}" -D"sonar.token=${{ secrets.SONAR_TOKEN }}"   

  raj-build-job:
    runs-on: macos-latest
    needs: raj-sast-job # it will wait for SAST job to finish
    steps:
      - name: just check general message
        run:  |
          echo "python version checking"
          python -V