name: raj app conatinerization pipeline
# Trigger -- when this pipeline should start
on:
  push:
    branches:
    - "dev"

# creating multiple jobs
jobs:
  raj-sast-job:
    runs-on: self-hosted
    steps:
    - name: checking docker version and sonarscanner
      run: |
        pwd
        whoami
        sonar-scanner --version
    - name: fetch git code
      uses: actions/checkout@v4

    - name: using local sonar-scanner

      run: "pwd\nsonar-scanner -D\"sonar.projectKey=raj-python-project\" -D\"sonar.sources=.\" -D\"sonar.host.url=${{ vars.SONAR_HOST_URL }}\" -D\"sonar.token=${{ secrets.SONAR_TOKEN }}\"   \n"
    - name: using upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: raj-artifact
        path: |
          .
          !**/.git*
          !**/*.md


  raj-build-job:
    runs-on: ubuntu-latest
    needs: raj-sast-job # it will wait for SAST job to finish
    steps:
    - name: just check general message
      run: |
        echo "docker related details"
        docker version
        docker-compose version

    
    - name: downloading artifacts

      uses: actions/download-artifact@v4
      with:
        name: raj-artifact
        path: .
    - name: docker compose to build and test
      run: |
        ls -a
        docker-compose up -d
        sleep 2
        docker-compose ps
    - name: trying to access health-check
      run: "curl -f http://localhost:1234/health.html"

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    
    - name: ecr-publish
      uses: bitovi/github-actions-ecr-publish@v0.1.0
      with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: us-east-1
          aws_ecr_repo_name: bmo-webui-app
          image_tag: rajappv1github