name: raj app conatinerization pipeline
# Trigger -- when this pipeline should start
on:
  push:
    branches:
    - "dev"

# creating multiple jobs
jobs:
  raj-code-checkjob:
    runs-on: ubuntu-latest
    steps:
      - name: checking only
        run:  |
          whoami
  raj-sast-job:
    runs-on: self-hosted
    needs: raj-code-checkjob # it will wait for job1 to finish
    steps:
      - name: checking docker version and sonarscanner
        run:  |
          pwd
          whoami
  raj-build-job:
    runs-on: macos-latest
    needs: raj-sast-job # it will wait for SAST job to finish
    steps:
      - name: just check general message
        run:  |
          echo "python version checking"
          python -V