name: raj app conatinerization pipeline
# Trigger -- when this pipeline should start
on:
  push:
    branches:
    - "dev"

# creating multiple jobs
jobs:
  raj-sast-job:
    runs-on: self-hosted
    steps:
      - name: checking docker version and sonarscanner
        run:  |
          pwd
          whoami
          sonar-scanner --version
      - name: fetch git code
        uses: actions/checkout@v4

      
      - name: using local sonar-scanner
        run:  |
          pwd
          sonar-scanner -D"sonar.projectKey=raj-python-project" -D"sonar.sources=." -D"sonar.host.url=${{ vars.SONAR_HOST_URL }}" -D"sonar.token=${{ secrets.SONAR_TOKEN }}"   
      - name: using upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: raj-artifact
          path:  |
            .
            !**/.git*
            !**/*.md


  raj-build-job:
    runs-on: macos-latest
    needs: raj-sast-job # it will wait for SAST job to finish
    steps:
      - name: just check general message
        run:  |
          echo "docker related details"
          docker version
          docker-compose version
      - name: downloading artifacts
        uses: actions/download-artifact@v4
        with:
          name: raj-artifact
          path: .
      - name : docker compose to build and test
        run:  |
          ls -a
          docker-compose up -d
          sleep 2
          docker-compose ps
      - name: trying to access health-check
        run: "curl -f http://localhost:1234/health.html"