# create pipeline with some name
name: raj app conatinerization pipeline
# Trigger -- when this pipeline should start
on:
  push:
    branches:
    - "main"

# jobs for performing operation
jobs:
  raj-image-build:
    runs-on: ubuntu-latest
    # this server will be provision by github backen for this job
    steps:
    - name: run some basic command on above server to do some verification
      run: |
        uname -r
        whoami
        cat /etc/os-release
        docker version
        docker-compose version
    - name: using pre-design github workflow to get copy gitrepo code to runners machine
      uses: actions/checkout@v4

    - name: verify github code and use docker compose to build and create
      run:  |
        ls  -a
        docker-compose up -d
        sleep 2
        docker-compose ps
    -  name: trying to access health-check
       run: |
            curl -f http://localhost:1234/health.html 
            echo "health-check is OK"


    -  name: try to login from runner to docker hub account
       run:  |
         docker login -u rajsumit2024 -p Cerelia@2024
         docker tag rajwebui:v1 docker.io/dockerashu/rajwebui.docker.io/dockerashu/rajwebui.version1
         #above command to make an alias of image to docker hub format
         docker push docker.io/rajsumit2024/rajwebui:version1
         docker logout



